#!/bin/sh

set -e

cd "$(dirname "$0")/.."

local_bin=".stack-work/dist/x86_64-linux/*/build/formalize/formalize"
app_name="formalize"
folders="web"
package_name="package.tar.gz"
remote="formalize"
deploy_path="/var/www/apps/${app_name}/app"

echo "==> Testing SSH connection..."
ssh $remote "uname -a"
echo "==> Connection OK"

echo "==> Creating deploy package..."
script/build
if [ -e $local_bin ]; then
  echo "==> Architecture OK"
else
  echo "==> Incorrect architecture. Can't deploy."
  exit 1
fi
cp $local_bin $app_name
tar -zcvf $package_name $folders $app_name
echo "==> Package created"

echo "==> Deploying to server..."
scp $package_name $remote:$deploy_path
CMD="\
cd ${deploy_path} &&\
supervisorctl stop ${app_name} &&\
rm -rf ${folders} ${app_name} &&\
tar -zxvf ${package_name} &&\
supervisorctl start ${app_name} &&\
rm ${package_name}"
ssh $remote $CMD
echo "==> Deployed"

echo "==> Cleaning up..."
rm $app_name
rm $package_name
echo "==> All done!"
