#!/bin/sh

cd "$(dirname "$0")/.."

stack_url="https://github.com/commercialhaskell/stack"
wkhtmltopdf_url="http://wkhtmltopdf.org/"

stack setup &> /dev/null
if [ $? -eq 0 ]; then
  echo "==> Stack:       OK"
else
  echo "==> You need to install 'stack'"
  echo "==> Check out ${stack_url}"
  exit 1
fi

wkhtmltopdf -V &> /dev/null
if [ $? -eq 0 ]; then
  echo "==> wkhtmltopdf: OK"
else
  echo "==> You need to install 'wkhtmltopdf'"
  echo "==> Check out ${wkhtmltopdf_url}"
  exit 1
fi

echo "==> Creating a folders for PDF files..."
mkdir -p files
mkdir -p test-files
echo "==> Setup done!"
